//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "audit_logs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "organizationId", column_type = "Text", nullable)]
    pub organization_id: Option<String>,
    #[sea_orm(column_name = "userId", column_type = "Text", nullable)]
    pub user_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub action: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub resource: Option<String>,
    #[sea_orm(column_name = "resourceId", column_type = "Text", nullable)]
    pub resource_id: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub details: Option<Json>,
    #[sea_orm(column_name = "ipAddress", column_type = "Text", nullable)]
    pub ip_address: Option<String>,
    #[sea_orm(column_name = "userAgent", column_type = "Text", nullable)]
    pub user_agent: Option<String>,
    #[sea_orm(column_name = "sessionId", column_type = "Text", nullable)]
    pub session_id: Option<String>,
    pub success: bool,
    #[sea_orm(column_name = "errorCode", column_type = "Text", nullable)]
    pub error_code: Option<String>,
    #[sea_orm(column_name = "errorMessage", column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub timestamp: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
