//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::FileStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "originalName", column_type = "Text")]
    pub original_name: String,
    #[sea_orm(column_name = "fileKey", column_type = "Text", unique)]
    pub file_key: String,
    #[sea_orm(column_name = "mimeType", column_type = "Text")]
    pub mime_type: String,
    pub size: i32,
    #[sea_orm(column_name = "userId", column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_name = "organizationId", column_type = "Text", nullable)]
    pub organization_id: Option<String>,
    #[sea_orm(column_name = "uploadDate")]
    pub upload_date: DateTime,
    #[sea_orm(column_name = "lastAccessed")]
    pub last_accessed: DateTime,
    #[sea_orm(column_name = "isPublic")]
    pub is_public: bool,
    pub status: FileStatus,
    #[sea_orm(column_name = "contentType", column_type = "Text", nullable)]
    pub content_type: Option<String>,
    #[sea_orm(column_name = "bucketName", column_type = "Text")]
    pub bucket_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub etag: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
