//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::InventoryTransactionType;
use super::sea_orm_active_enums::PurchaseStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "inventory_transactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "productId", column_type = "Text")]
    pub product_id: String,
    pub r#type: InventoryTransactionType,
    #[sea_orm(column_type = "Double")]
    pub quantity: f64,
    #[sea_orm(column_name = "inventoryBatchId", column_type = "Text", nullable)]
    pub inventory_batch_id: Option<String>,
    #[sea_orm(column_name = "organizationId", column_type = "Text")]
    pub organization_id: String,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "deletedAt")]
    pub deleted_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub local_ref_id: Option<String>,
    pub status: PurchaseStatus,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::inventory_batches::Entity",
        from = "Column::InventoryBatchId",
        to = "super::inventory_batches::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    InventoryBatches,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Products,
}

impl Related<super::inventory_batches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryBatches.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}
