//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::OrganizationType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "organizations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub code: Option<String>,
    pub r#type: OrganizationType,
    #[sea_orm(column_name = "parentId", column_type = "Text", nullable)]
    pub parent_id: Option<String>,
    #[sea_orm(column_name = "isActive")]
    pub is_active: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub phone: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub address: Option<String>,
    #[sea_orm(column_name = "taxId", column_type = "Text", nullable)]
    pub tax_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub timezone: String,
    #[sea_orm(column_type = "Text")]
    pub currency: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub settings: Json,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_name = "deletedAt")]
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::audit_logs::Entity")]
    AuditLogs,
    #[sea_orm(has_many = "super::brands::Entity")]
    Brands,
    #[sea_orm(has_many = "super::cash_drawers::Entity")]
    CashDrawers,
    #[sea_orm(has_many = "super::categories::Entity")]
    Categories,
    #[sea_orm(has_many = "super::customers::Entity")]
    Customers,
    #[sea_orm(has_many = "super::discounts::Entity")]
    Discounts,
    #[sea_orm(has_many = "super::files::Entity")]
    Files,
    #[sea_orm(has_many = "super::finances::Entity")]
    Finances,
    #[sea_orm(has_many = "super::inventory_batches::Entity")]
    InventoryBatches,
    #[sea_orm(has_many = "super::inventory_transactions::Entity")]
    InventoryTransactions,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::payable_realizations::Entity")]
    PayableRealizations,
    #[sea_orm(has_many = "super::payables::Entity")]
    Payables,
    #[sea_orm(has_many = "super::payment_methods::Entity")]
    PaymentMethods,
    #[sea_orm(has_many = "super::product_prices::Entity")]
    ProductPrices,
    #[sea_orm(has_many = "super::product_variants::Entity")]
    ProductVariants,
    #[sea_orm(has_many = "super::products::Entity")]
    Products,
    #[sea_orm(has_many = "super::purchase_return_items::Entity")]
    PurchaseReturnItems,
    #[sea_orm(has_many = "super::purchase_returns::Entity")]
    PurchaseReturns,
    #[sea_orm(has_many = "super::purchases::Entity")]
    Purchases,
    #[sea_orm(has_many = "super::receivable_realizations::Entity")]
    ReceivableRealizations,
    #[sea_orm(has_many = "super::receivables::Entity")]
    Receivables,
    #[sea_orm(has_many = "super::refresh_tokens::Entity")]
    RefreshTokens,
    #[sea_orm(has_many = "super::roles::Entity")]
    Roles,
    #[sea_orm(has_many = "super::shifts::Entity")]
    Shifts,
    #[sea_orm(has_many = "super::stock_opname_items::Entity")]
    StockOpnameItems,
    #[sea_orm(has_many = "super::stock_opnames::Entity")]
    StockOpnames,
    #[sea_orm(has_many = "super::suppliers::Entity")]
    Suppliers,
    #[sea_orm(has_many = "super::transaction_items::Entity")]
    TransactionItems,
    #[sea_orm(has_many = "super::transactions::Entity")]
    Transactions,
    #[sea_orm(has_many = "super::user_organizations::Entity")]
    UserOrganizations,
    #[sea_orm(has_many = "super::users::Entity")]
    Users,
}

impl Related<super::audit_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuditLogs.def()
    }
}

impl Related<super::brands::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Brands.def()
    }
}

impl Related<super::cash_drawers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CashDrawers.def()
    }
}

impl Related<super::categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Categories.def()
    }
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::discounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Discounts.def()
    }
}

impl Related<super::files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Files.def()
    }
}

impl Related<super::finances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Finances.def()
    }
}

impl Related<super::inventory_batches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryBatches.def()
    }
}

impl Related<super::inventory_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryTransactions.def()
    }
}

impl Related<super::payable_realizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PayableRealizations.def()
    }
}

impl Related<super::payables::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Payables.def()
    }
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}

impl Related<super::product_prices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductPrices.def()
    }
}

impl Related<super::product_variants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductVariants.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::purchase_return_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseReturnItems.def()
    }
}

impl Related<super::purchase_returns::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseReturns.def()
    }
}

impl Related<super::purchases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Purchases.def()
    }
}

impl Related<super::receivable_realizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReceivableRealizations.def()
    }
}

impl Related<super::receivables::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Receivables.def()
    }
}

impl Related<super::refresh_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefreshTokens.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Roles.def()
    }
}

impl Related<super::shifts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Shifts.def()
    }
}

impl Related<super::stock_opname_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StockOpnameItems.def()
    }
}

impl Related<super::stock_opnames::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StockOpnames.def()
    }
}

impl Related<super::suppliers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Suppliers.def()
    }
}

impl Related<super::transaction_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionItems.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl Related<super::user_organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserOrganizations.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_organizations::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::user_organizations::Relation::Organizations
                .def()
                .rev(),
        )
    }
}
