//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::ProductType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "products")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub barcode: Option<String>,
    #[sea_orm(column_name = "purchasePrice", column_type = "Double")]
    pub purchase_price: f64,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_name = "isFavorite")]
    pub is_favorite: bool,
    #[sea_orm(column_name = "categoryId", column_type = "Text")]
    pub category_id: String,
    #[sea_orm(column_name = "brandId", column_type = "Text", nullable)]
    pub brand_id: Option<String>,
    #[sea_orm(column_name = "organizationId", column_type = "Text")]
    pub organization_id: String,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_name = "deletedAt")]
    pub deleted_at: Option<DateTime>,
    #[sea_orm(column_name = "isActive")]
    pub is_active: bool,
    #[sea_orm(column_name = "minimumStock", column_type = "Double")]
    pub minimum_stock: f64,
    pub r#type: ProductType,
    #[sea_orm(column_type = "Text", nullable)]
    pub unit: Option<String>,
    #[sea_orm(column_name = "discountId", column_type = "Text", nullable)]
    pub discount_id: Option<String>,
    #[sea_orm(column_name = "supplierId", column_type = "Text", nullable)]
    pub supplier_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::brands::Entity",
        from = "Column::BrandId",
        to = "super::brands::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Brands,
    #[sea_orm(
        belongs_to = "super::categories::Entity",
        from = "Column::CategoryId",
        to = "super::categories::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Categories,
    #[sea_orm(
        belongs_to = "super::discounts::Entity",
        from = "Column::DiscountId",
        to = "super::discounts::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Discounts,
    #[sea_orm(has_many = "super::inventory_batches::Entity")]
    InventoryBatches,
    #[sea_orm(has_many = "super::inventory_transactions::Entity")]
    InventoryTransactions,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(has_many = "super::product_prices::Entity")]
    ProductPrices,
    #[sea_orm(has_many = "super::product_variants::Entity")]
    ProductVariants,
    #[sea_orm(has_many = "super::purchase_return_items::Entity")]
    PurchaseReturnItems,
    #[sea_orm(has_many = "super::stock_opname_items::Entity")]
    StockOpnameItems,
    #[sea_orm(
        belongs_to = "super::suppliers::Entity",
        from = "Column::SupplierId",
        to = "super::suppliers::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Suppliers,
    #[sea_orm(has_many = "super::transaction_items::Entity")]
    TransactionItems,
}

impl Related<super::brands::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Brands.def()
    }
}

impl Related<super::categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Categories.def()
    }
}

impl Related<super::discounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Discounts.def()
    }
}

impl Related<super::inventory_batches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryBatches.def()
    }
}

impl Related<super::inventory_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryTransactions.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::product_prices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductPrices.def()
    }
}

impl Related<super::product_variants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductVariants.def()
    }
}

impl Related<super::purchase_return_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseReturnItems.def()
    }
}

impl Related<super::stock_opname_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StockOpnameItems.def()
    }
}

impl Related<super::suppliers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Suppliers.def()
    }
}

impl Related<super::transaction_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionItems.def()
    }
}
