//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "AuthProvider")]
pub enum AuthProvider {
    #[sea_orm(string_value = "LOCAL")]
    Local,
    #[sea_orm(string_value = "GOOGLE")]
    Google,
    #[sea_orm(string_value = "FACEBOOK")]
    Facebook,
    #[sea_orm(string_value = "APPLE")]
    Apple,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "CustomerCategory")]
pub enum CustomerCategory {
    #[sea_orm(string_value = "WHOLESALE")]
    Wholesale,
    #[sea_orm(string_value = "RETAIL")]
    Retail,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "DiscountType")]
pub enum DiscountType {
    #[sea_orm(string_value = "PERCENTAGE")]
    Percentage,
    #[sea_orm(string_value = "FLAT")]
    Flat,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "FileStatus")]
pub enum FileStatus {
    #[sea_orm(string_value = "ACTIVE")]
    Active,
    #[sea_orm(string_value = "DELETED")]
    Deleted,
    #[sea_orm(string_value = "QUARANTINED")]
    Quarantined,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "FinanceExpensesType"
)]
pub enum FinanceExpensesType {
    #[sea_orm(string_value = "STORE_EXPENSES")]
    StoreExpenses,
    #[sea_orm(string_value = "SUPPLIES")]
    Supplies,
    #[sea_orm(string_value = "EQUIPMENT")]
    Equipment,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "FinanceStatus")]
pub enum FinanceStatus {
    #[sea_orm(string_value = "DRAFT")]
    Draft,
    #[sea_orm(string_value = "COMPLETED")]
    Completed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "FinanceType")]
pub enum FinanceType {
    #[sea_orm(string_value = "INCOME")]
    Income,
    #[sea_orm(string_value = "EXPENSES")]
    Expenses,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "InventoryTransactionType"
)]
pub enum InventoryTransactionType {
    #[sea_orm(string_value = "PURCHASE")]
    Purchase,
    #[sea_orm(string_value = "SALE")]
    Sale,
    #[sea_orm(string_value = "RETURN_PURCHASE")]
    ReturnPurchase,
    #[sea_orm(string_value = "STOCK_OPNAME")]
    StockOpname,
    #[sea_orm(string_value = "ADJUSTMENT")]
    Adjustment,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "OrganizationType")]
pub enum OrganizationType {
    #[sea_orm(string_value = "COMPANY")]
    Company,
    #[sea_orm(string_value = "BRANCH")]
    Branch,
    #[sea_orm(string_value = "PROJECT")]
    Project,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "PaymentType")]
pub enum PaymentType {
    #[sea_orm(string_value = "CASH")]
    Cash,
    #[sea_orm(string_value = "DEBT")]
    Debt,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "PriceType")]
pub enum PriceType {
    #[sea_orm(string_value = "RETAIL")]
    Retail,
    #[sea_orm(string_value = "WHOLESALE")]
    Wholesale,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ProductType")]
pub enum ProductType {
    #[sea_orm(string_value = "DEFAULT")]
    Default,
    #[sea_orm(string_value = "MULTIUNIT")]
    Multiunit,
    #[sea_orm(string_value = "VARIANTS")]
    Variants,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "PurchaseReturnType")]
pub enum PurchaseReturnType {
    #[sea_orm(string_value = "CASH")]
    Cash,
    #[sea_orm(string_value = "ITEM")]
    Item,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "PurchaseStatus")]
pub enum PurchaseStatus {
    #[sea_orm(string_value = "DRAFT")]
    Draft,
    #[sea_orm(string_value = "COMPLETED")]
    Completed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ShiftStatus")]
pub enum ShiftStatus {
    #[sea_orm(string_value = "ACTIVE")]
    Active,
    #[sea_orm(string_value = "CLOSED")]
    Closed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "StockOpnameStatus")]
pub enum StockOpnameStatus {
    #[sea_orm(string_value = "DIFFERENCE")]
    Difference,
    #[sea_orm(string_value = "DONE")]
    Done,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "TransactionStatus")]
pub enum TransactionStatus {
    #[sea_orm(string_value = "DRAFT")]
    Draft,
    #[sea_orm(string_value = "COMPLETED")]
    Completed,
}
