//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::ShiftStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "shifts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub local_ref_id: String,
    #[sea_orm(column_name = "cashDrawerId", column_type = "Text")]
    pub cash_drawer_id: String,
    #[sea_orm(column_name = "userId", column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_name = "startTime")]
    pub start_time: DateTime,
    #[sea_orm(column_name = "endTime")]
    pub end_time: Option<DateTime>,
    #[sea_orm(column_name = "initialBalance", column_type = "Double")]
    pub initial_balance: f64,
    #[sea_orm(column_name = "finalBalance", column_type = "Double", nullable)]
    pub final_balance: Option<f64>,
    #[sea_orm(column_name = "expectedBalance", column_type = "Double", nullable)]
    pub expected_balance: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub difference: Option<f64>,
    pub status: ShiftStatus,
    #[sea_orm(column_type = "Text", nullable)]
    pub note: Option<String>,
    #[sea_orm(column_name = "organizationId", column_type = "Text")]
    pub organization_id: String,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_name = "deletedAt")]
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cash_drawers::Entity",
        from = "Column::CashDrawerId",
        to = "super::cash_drawers::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    CashDrawers,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Users,
}

impl Related<super::cash_drawers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CashDrawers.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
