//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "stock_opname_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "stockOpnameId", column_type = "Text")]
    pub stock_opname_id: String,
    #[sea_orm(column_name = "productId", column_type = "Text")]
    pub product_id: String,
    #[sea_orm(column_name = "quantitySystem", column_type = "Double")]
    pub quantity_system: f64,
    #[sea_orm(column_name = "quantityPhysical", column_type = "Double")]
    pub quantity_physical: f64,
    #[sea_orm(column_type = "Double")]
    pub difference: f64,
    #[sea_orm(column_name = "purchasePrice", column_type = "Double")]
    pub purchase_price: f64,
    #[sea_orm(column_name = "financialImpact", column_type = "Double")]
    pub financial_impact: f64,
    #[sea_orm(column_name = "organizationId", column_type = "Text")]
    pub organization_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Products,
    #[sea_orm(
        belongs_to = "super::stock_opnames::Entity",
        from = "Column::StockOpnameId",
        to = "super::stock_opnames::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    StockOpnames,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::stock_opnames::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StockOpnames.def()
    }
}
