//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::StockOpnameStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "stock_opnames")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub date: DateTime,
    #[sea_orm(column_type = "Text", nullable)]
    pub note: Option<String>,
    pub status: StockOpnameStatus,
    #[sea_orm(column_name = "totalGain", column_type = "Double")]
    pub total_gain: f64,
    #[sea_orm(column_name = "totalLoss", column_type = "Double")]
    pub total_loss: f64,
    #[sea_orm(column_name = "createdBy", column_type = "Text", nullable)]
    pub created_by: Option<String>,
    #[sea_orm(column_name = "organizationId", column_type = "Text")]
    pub organization_id: String,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub local_ref_id: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_name = "deletedAt")]
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(has_many = "super::stock_opname_items::Entity")]
    StockOpnameItems,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::stock_opname_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StockOpnameItems.def()
    }
}
