//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::TransactionStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "transactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub local_ref_id: String,
    #[sea_orm(column_name = "customerId", column_type = "Text", nullable)]
    pub customer_id: Option<String>,
    #[sea_orm(column_name = "totalAmount", column_type = "Double")]
    pub total_amount: f64,
    #[sea_orm(column_name = "totalPaid", column_type = "Double")]
    pub total_paid: f64,
    #[sea_orm(column_name = "paymentTypeId", column_type = "Text")]
    pub payment_type_id: String,
    #[sea_orm(column_name = "transactionDate")]
    pub transaction_date: DateTime,
    pub status: TransactionStatus,
    #[sea_orm(column_type = "Text", nullable)]
    pub note: Option<String>,
    #[sea_orm(column_name = "organizationId", column_type = "Text")]
    pub organization_id: String,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_name = "deletedAt")]
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::customers::Entity",
        from = "Column::CustomerId",
        to = "super::customers::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Customers,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::payment_methods::Entity",
        from = "Column::PaymentTypeId",
        to = "super::payment_methods::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    PaymentMethods,
    #[sea_orm(has_many = "super::transaction_items::Entity")]
    TransactionItems,
}

impl Related<super::customers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customers.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}

impl Related<super::transaction_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionItems.def()
    }
}
