//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::AuthProvider;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub username: String,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub password: Option<String>,
    pub provider: AuthProvider,
    #[sea_orm(column_name = "firstName", column_type = "Text", nullable)]
    pub first_name: Option<String>,
    #[sea_orm(column_name = "lastName", column_type = "Text", nullable)]
    pub last_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub phone: Option<String>,
    #[sea_orm(column_name = "isActive")]
    pub is_active: bool,
    #[sea_orm(column_name = "isLocked")]
    pub is_locked: bool,
    #[sea_orm(column_name = "lockReason", column_type = "Text", nullable)]
    pub lock_reason: Option<String>,
    #[sea_orm(column_name = "selectedOrganizationId", column_type = "Text", nullable)]
    pub selected_organization_id: Option<String>,
    #[sea_orm(column_name = "createdById", column_type = "Text", nullable)]
    pub created_by_id: Option<String>,
    #[sea_orm(column_name = "lastLoginAt")]
    pub last_login_at: Option<DateTime>,
    #[sea_orm(column_name = "passwordChangedAt")]
    pub password_changed_at: Option<DateTime>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::audit_logs::Entity")]
    AuditLogs,
    #[sea_orm(has_many = "super::files::Entity")]
    Files,
    #[sea_orm(has_many = "super::finances::Entity")]
    Finances,
    #[sea_orm(has_many = "super::oauth_accounts::Entity")]
    OauthAccounts,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::SelectedOrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Organizations,
    #[sea_orm(has_many = "super::receivables::Entity")]
    Receivables,
    #[sea_orm(has_many = "super::refresh_tokens::Entity")]
    RefreshTokens,
    #[sea_orm(has_many = "super::shifts::Entity")]
    Shifts,
    #[sea_orm(has_many = "super::user_organizations::Entity")]
    UserOrganizations,
    #[sea_orm(has_many = "super::user_roles::Entity")]
    UserRoles,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::CreatedById",
        to = "Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    SelfRef,
}

impl Related<super::audit_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuditLogs.def()
    }
}

impl Related<super::files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Files.def()
    }
}

impl Related<super::finances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Finances.def()
    }
}

impl Related<super::oauth_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OauthAccounts.def()
    }
}

impl Related<super::receivables::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Receivables.def()
    }
}

impl Related<super::refresh_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefreshTokens.def()
    }
}

impl Related<super::shifts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Shifts.def()
    }
}

impl Related<super::user_organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserOrganizations.def()
    }
}

impl Related<super::user_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRoles.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_organizations::Relation::Organizations.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_organizations::Relation::Users.def().rev())
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_roles::Relation::Roles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_roles::Relation::Users.def().rev())
    }
}
