/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request body for adjusting stock levels. */
        AdjustStockRequest: {
            /** @description Type of adjustment (purchase, sale, adjustment, damage, return). */
            movementType: string;
            /** @description Optional notes. */
            notes?: string | null;
            /**
             * Format: int32
             * @description Signed quantity to adjust (positive = add, negative = remove).
             */
            quantity: number;
            /** @description Reason for the adjustment. */
            reason: string;
            /** @description Optional reference string. */
            reference?: string | null;
        };
        /** @description Cost breakdown response for a BOM. */
        BomCostBreakdownResponse: {
            /** @description BOM ID. */
            bomId: string;
            /** @description Item cost details. */
            items: components["schemas"]["BomItemCostResponse"][];
            /**
             * Format: int64
             * @description Total cost.
             */
            totalCost: number;
        };
        /** @description Item cost details in a BOM cost breakdown. */
        BomItemCostResponse: {
            /** @description Component product ID. */
            componentProductId: string;
            /**
             * Format: int64
             * @description Line cost.
             */
            lineCost: number;
            /**
             * Format: double
             * @description Quantity.
             */
            quantity: number;
            /** @description Unit of measure. */
            unit: string;
            /**
             * Format: int64
             * @description Unit cost.
             */
            unitCost: number;
            /**
             * Format: double
             * @description Waste percentage.
             */
            wastePercent: number;
        };
        /** @description BOM item response. */
        BomItemResponse: {
            /** @description Parent BOM ID. */
            bomId: string;
            /** @description Component product ID. */
            componentProductId: string;
            /** @description Creation timestamp. */
            createdAt: string;
            /** @description Unique identifier. */
            id: string;
            /**
             * Format: int64
             * @description Line cost (qty × unit_cost).
             */
            lineCost?: number | null;
            /** @description Optional notes. */
            notes?: string | null;
            /**
             * Format: double
             * @description Quantity needed.
             */
            quantity: number;
            /** @description Unit of measure. */
            unit: string;
            /**
             * Format: int64
             * @description Unit cost snapshot.
             */
            unitCost?: number | null;
            /** @description Last update timestamp. */
            updatedAt: string;
            /**
             * Format: double
             * @description Waste percentage.
             */
            wastePercent: number;
            /**
             * Format: double
             * @description Yield percentage.
             */
            yieldPercent: number;
        };
        /** @description BOM response for GET endpoints. */
        BomResponse: {
            /** @description Creation timestamp. */
            createdAt: string;
            /** @description User who created this BOM. */
            createdBy?: string | null;
            /** @description Effective from date. */
            effectiveFrom?: string | null;
            /** @description Effective to date. */
            effectiveTo?: string | null;
            /** @description Unique identifier. */
            id: string;
            /** @description Name of the BOM. */
            name: string;
            /** @description Optional notes. */
            notes?: string | null;
            /** @description Organization ID. */
            organizationId: string;
            /** @description Product ID this BOM belongs to. */
            productId: string;
            /** @description Status (draft, active, archived). */
            status: string;
            /**
             * Format: int64
             * @description Total cost in smallest currency unit.
             */
            totalCost?: number | null;
            /** @description Last update timestamp. */
            updatedAt: string;
            /** @description Version string. */
            version: string;
        };
        /** @description BOM with its items combined. */
        BomWithItemsResponse: components["schemas"]["BomResponse"] & {
            /** @description List of BOM items. */
            items: components["schemas"]["BomItemResponse"][];
        };
        /** @description Full brand response DTO. */
        BrandResponse: {
            /** @description Record creation timestamp. */
            createdAt: string;
            /** @description User who created this brand. */
            createdBy?: string | null;
            /** @description Optional description. */
            description?: string | null;
            /** @description Brand ID. */
            id: string;
            /** @description Whether the brand is active. */
            isActive: boolean;
            /** @description Optional logo URL. */
            logo?: string | null;
            /** @description Brand name. */
            name: string;
            /** @description Owning organization ID. */
            organizationId: string;
            /** @description URL-friendly slug. */
            slug: string;
            /** @description Record last-update timestamp. */
            updatedAt: string;
            /** @description Optional website URL. */
            website?: string | null;
        };
        /** @description Abbreviated brand info embedded in product responses. */
        BrandSummary: {
            /** @description Brand ID. */
            id: string;
            /** @description Brand name. */
            name: string;
        };
        /** @description Full category response DTO. */
        CategoryResponse: {
            /** @description Record creation timestamp. */
            createdAt: string;
            /** @description User who created this category. */
            createdBy?: string | null;
            /** @description Optional description. */
            description?: string | null;
            /** @description Category ID. */
            id: string;
            /** @description Optional image URL. */
            imageUrl?: string | null;
            /** @description Whether the category is active. */
            isActive: boolean;
            /** @description Category name. */
            name: string;
            /** @description Owning organization ID. */
            organizationId: string;
            /** @description Optional parent category ID for hierarchy. */
            parentId?: string | null;
            /** @description URL-friendly slug. */
            slug: string;
            /**
             * Format: int64
             * @description Display sort order.
             */
            sortOrder: number;
            /** @description Record last-update timestamp. */
            updatedAt: string;
        };
        /** @description Abbreviated category info embedded in product responses. */
        CategorySummary: {
            /** @description Category ID. */
            id: string;
            /** @description Category name. */
            name: string;
        };
        /** @description Consumption record response. */
        ConsumptionResponse: {
            /**
             * Format: double
             * @description Actual quantity consumed.
             */
            actualQuantity: number;
            /** @description Component product ID. */
            componentProductId: string;
            /** @description Creation timestamp. */
            createdAt: string;
            /** @description Unique identifier. */
            id: string;
            /**
             * Format: double
             * @description Planned quantity.
             */
            plannedQuantity: number;
            /** @description Production run ID. */
            productionRunId: string;
            /** @description Unit of measure. */
            unit: string;
            /**
             * Format: double
             * @description Waste quantity.
             */
            wasteQuantity: number;
        };
        /** @description Request to create a BOM item. */
        CreateBomItemRequest: {
            /** @description Component product ID. */
            componentProductId: string;
            /** @description Optional notes. */
            notes?: string | null;
            /**
             * Format: double
             * @description Quantity needed.
             */
            quantity: number;
            /** @description Unit of measure. */
            unit: string;
            /**
             * Format: double
             * @description Waste percentage (optional, defaults to 0).
             */
            wastePercent?: number | null;
            /**
             * Format: double
             * @description Yield percentage (optional, defaults to 100).
             */
            yieldPercent?: number | null;
        };
        /** @description Request to create a BOM. */
        CreateBomRequest: {
            /** @description Effective from date (ISO 8601). */
            effectiveFrom?: string | null;
            /** @description Effective to date (ISO 8601). */
            effectiveTo?: string | null;
            /** @description Name of the BOM. */
            name: string;
            /** @description Optional notes. */
            notes?: string | null;
            /** @description Product ID this BOM belongs to. */
            productId: string;
            /** @description Status (optional, defaults to "draft"). */
            status?: string | null;
            /** @description Version string (optional, defaults to "1.0.0"). */
            version?: string | null;
        };
        /** @description Request body for creating a brand. */
        CreateBrandRequest: {
            /** @description Optional description. */
            description?: string | null;
            /** @description Optional logo URL. */
            logo?: string | null;
            /** @description Brand name. */
            name: string;
            /** @description Optional website URL. */
            website?: string | null;
        };
        /** @description Request body for creating a category. */
        CreateCategoryRequest: {
            /** @description Optional description. */
            description?: string | null;
            /** @description Optional image URL. */
            imageUrl?: string | null;
            /** @description Category name. */
            name: string;
            /** @description Optional parent category ID. */
            parentId?: string | null;
        };
        /** @description Request to create a consumption record. */
        CreateConsumptionRequest: {
            /**
             * Format: double
             * @description Actual quantity consumed.
             */
            actualQuantity: number;
            /** @description Component product ID. */
            componentProductId: string;
            /**
             * Format: double
             * @description Planned quantity.
             */
            plannedQuantity: number;
            /** @description Unit of measure. */
            unit: string;
            /**
             * Format: double
             * @description Waste quantity (optional, defaults to 0).
             */
            wasteQuantity?: number | null;
        };
        /** @description Order item within a create order request. */
        CreateOrderItemRequest: {
            /** @description Optional custom item name override. */
            itemName?: string | null;
            /** @description Product ID. */
            productId: string;
            /**
             * Format: int32
             * @description Quantity to order.
             */
            quantity: number;
        };
        /** @description Request body for creating an order. */
        CreateOrderRequest: {
            /** @description Optional walk-in customer name. */
            customerName?: string | null;
            /** @description Order items. */
            items: components["schemas"]["CreateOrderItemRequest"][];
            /** @description Optional notes. */
            notes?: string | null;
            /** @description Optional payment method. */
            paymentMethod?: string | null;
            /** @description Optional table number. */
            tableNumber?: string | null;
            /** @description Order type (dine_in, takeaway, delivery). */
            type: string;
        };
        /** @description Request body for creating an organization. */
        CreateOrgRequest: {
            /** @description Optional physical address. */
            address?: string | null;
            /** @description Optional city. */
            city?: string | null;
            /** @description Optional organization code. */
            code?: string | null;
            /** @description Optional country. */
            country?: string | null;
            /** @description Optional description. */
            description?: string | null;
            /** @description Optional contact email. */
            email?: string | null;
            /** @description Optional logo URL. */
            logo?: string | null;
            /** @description Organization name. */
            name: string;
            /** @description Optional parent organization ID. */
            parentId?: string | null;
            /** @description Optional contact phone. */
            phone?: string | null;
            /** @description Optional postal code. */
            postalCode?: string | null;
            /** @description Optional business registration number. */
            registrationNumber?: string | null;
            /** @description Optional JSON settings. */
            settings?: unknown;
            /** @description Optional state/province. */
            state?: string | null;
            /** @description Optional tax identification number. */
            taxNumber?: string | null;
            /** @description Organization type (e.g. "restaurant", "retail"). */
            type: string;
            /** @description Optional website URL. */
            website?: string | null;
        };
        /** @description Request body for creating a product. */
        CreateProductRequest: {
            /** @description Optional barcode. */
            barcode?: string | null;
            /**
             * Format: int64
             * @description Base selling price in smallest currency unit.
             */
            basePrice: number;
            /** @description Optional brand ID. */
            brandId?: string | null;
            /** @description Optional category ID. */
            categoryId?: string | null;
            /**
             * Format: int64
             * @description Optional cost price.
             */
            costPrice?: number | null;
            /** @description Optional product description. */
            description?: string | null;
            /** @description Optional dimensions as JSON. */
            dimensions?: unknown;
            /** @description Optional image URL. */
            imageUrl?: string | null;
            /** @description Whether the product is featured (default false). */
            isFeatured?: boolean | null;
            /**
             * Format: int64
             * @description Optional minimum stock level.
             */
            minStockLevel?: number | null;
            /** @description Product name. */
            name: string;
            /** @description Stock keeping unit (unique within organization). */
            sku: string;
            /** @description Optional tags for search and filtering. */
            tags?: string[] | null;
            /** @description Whether to track inventory (default false). */
            trackInventory?: boolean | null;
            /**
             * Format: double
             * @description Optional weight in kilograms.
             */
            weight?: number | null;
        };
        /** @description Request to create a production run. */
        CreateProductionRunRequest: {
            /** @description Completed timestamp (ISO 8601). */
            completedAt?: string | null;
            /**
             * Format: int64
             * @description Estimated cost (optional).
             */
            estimatedCost?: number | null;
            /**
             * Format: double
             * @description Quantity to produce.
             */
            quantityProduced: number;
            /** @description Started timestamp (ISO 8601). */
            startedAt?: string | null;
            /** @description Status (optional, defaults to "planned"). */
            status?: string | null;
        };
        /** @description Request body for creating a role. */
        CreateRoleRequest: {
            /** @description Whether the role should be active immediately. */
            isActive?: boolean | null;
            /** @description Role name. */
            name: string;
            /** @description JSON permissions to assign. */
            permissions: unknown;
        };
        /** @description Request body for creating a user. */
        CreateUserRequest: {
            /** @description Email address. */
            email: string;
            /** @description Full name. */
            fullName: string;
            /** @description Whether the user should be active immediately. */
            isActive?: boolean | null;
            /** @description Plaintext password (will be hashed before storage). */
            password: string;
            /** @description Role ID to assign. */
            roleId: string;
        };
        /** @description Active sort filters echoed back to the frontend. */
        ListFilters: {
            /** @description Column used for sorting. */
            sortBy: string;
            /** @description Sort direction (`asc` or `desc`). */
            sortOrder: string;
        };
        /** @description Request body for `POST /api/auth/login`. */
        LoginRequest: {
            /**
             * @description User email address.
             * @example admin@sakaloka.id
             */
            email: string;
            /**
             * @description Plaintext password.
             * @example sakaloka-dev-01
             */
            password: string;
        };
        /** @description Successful login / refresh response. */
        LoginResponse: {
            /** @description Short-lived access JWT. */
            access_token: string;
            /** @description Long-lived refresh token. */
            refresh_token: string;
            /** @description Authenticated user profile. */
            user: components["schemas"]["UserProfile"];
        };
        /** @description POS menu item DTO (product + pricing for the order screen). */
        MenuResponse: {
            /**
             * Format: int64
             * @description Base selling price.
             */
            basePrice: number;
            /** @description Category ID. */
            categoryId?: string | null;
            /** @description Category name (if resolved). */
            categoryName?: string | null;
            /** @description Product ID. */
            id: string;
            /** @description Image URL. */
            imageUrl?: string | null;
            /** @description Whether the product is featured. */
            isFeatured: boolean;
            /** @description Product name. */
            name: string;
            /** @description Product SKU. */
            sku: string;
        };
        /** @description Single order item response DTO. */
        OrderItemResponse: {
            /** @description Record creation timestamp. */
            createdAt: string;
            /**
             * Format: int64
             * @description Discount applied to this line item.
             */
            discountAmount: number;
            /** @description Order item ID. */
            id: string;
            /** @description Item name snapshot. */
            itemName: string;
            /** @description Optional item-level notes. */
            notes?: string | null;
            /** @description Parent order ID. */
            orderId: string;
            /** @description Product ID. */
            productId: string;
            /**
             * Format: int32
             * @description Quantity ordered.
             */
            quantity: number;
            /**
             * Format: int64
             * @description Total price for this line.
             */
            totalPrice: number;
            /**
             * Format: int64
             * @description Unit price at time of order.
             */
            unitPrice: number;
        };
        /** @description Full order response DTO. */
        OrderResponse: {
            /** @description Record creation timestamp. */
            createdAt: string;
            /** @description User who created this order. */
            createdBy?: string | null;
            /** @description Optional customer user ID. */
            customerId?: string | null;
            /** @description Walk-in customer name. */
            customerName?: string | null;
            /**
             * Format: int64
             * @description Discount amount.
             */
            discountAmount: number;
            /** @description Order ID. */
            id: string;
            /** @description Order items (populated when fetching a single order). */
            items?: components["schemas"]["OrderItemResponse"][] | null;
            /** @description Order notes. */
            notes?: string | null;
            /** @description Unique order number. */
            orderNumber: string;
            /** @description Organization ID. */
            organizationId: string;
            /**
             * Format: int64
             * @description Amount already paid.
             */
            paidAmount: number;
            /** @description Payment method. */
            paymentMethod?: string | null;
            /** @description Payment status. */
            paymentStatus: string;
            /** @description Order status. */
            status: string;
            /**
             * Format: int64
             * @description Subtotal before tax/discounts.
             */
            subtotal: number;
            /** @description Table number for dine-in orders. */
            tableNumber?: string | null;
            /**
             * Format: int64
             * @description Tax amount.
             */
            taxAmount: number;
            /**
             * Format: int64
             * @description Total amount after tax and discounts.
             */
            totalAmount: number;
            /** @description Order type (dine_in, takeaway, delivery). */
            type: string;
            /** @description Record last-update timestamp. */
            updatedAt: string;
            /** @description User who last updated this order. */
            updatedBy?: string | null;
        };
        /** @description Abbreviated organization data included in auth responses. */
        OrgSummary: {
            /** @description Organization ID. */
            id: string;
            /** @description Organization name. */
            name: string;
            /** @description Organization type. */
            type: string;
        };
        /** @description Full organization response DTO. */
        OrganizationResponse: {
            /** @description Optional physical address. */
            address?: string | null;
            /** @description Optional city. */
            city?: string | null;
            /** @description Optional organization code. */
            code?: string | null;
            /** @description Optional country. */
            country?: string | null;
            /** @description Record creation timestamp. */
            createdAt: string;
            /** @description Optional description. */
            description?: string | null;
            /** @description Optional contact email. */
            email?: string | null;
            /** @description Organization ID. */
            id: string;
            /** @description Whether the organization is active. */
            isActive: boolean;
            /** @description Optional logo URL. */
            logo?: string | null;
            /** @description Organization name. */
            name: string;
            /** @description Optional owner user ID. */
            ownerId?: string | null;
            /** @description Optional parent organization ID. */
            parentId?: string | null;
            /** @description Optional contact phone. */
            phone?: string | null;
            /** @description Optional postal code. */
            postalCode?: string | null;
            /** @description Optional business registration number. */
            registrationNumber?: string | null;
            /** @description Optional JSON settings. */
            settings?: unknown;
            /** @description Optional state/province. */
            state?: string | null;
            /** @description Optional tax identification number. */
            taxNumber?: string | null;
            /** @description Organization type. */
            type: string;
            /** @description Record last-update timestamp. */
            updatedAt: string;
            /** @description Optional website URL. */
            website?: string | null;
        };
        /** @description Pagination metadata matching Venus `IPageMeta`. */
        PageMeta: {
            /** @description Whether a next page exists. */
            hasNextPage: boolean;
            /** @description Whether a previous page exists. */
            hasPrevPage: boolean;
            /**
             * Format: int64
             * @description Items per page.
             */
            limit: number;
            /**
             * Format: int64
             * @description Current page number (1-indexed).
             */
            page: number;
            /**
             * Format: int64
             * @description Total number of pages.
             */
            pages: number;
            /**
             * Format: int64
             * @description Total number of matching records.
             */
            total: number;
        };
        /** @description UI-facing permission action metadata. */
        PermissionActionResponse: {
            /** @description Action key stored under a module. */
            key: string;
            /** @description Human-readable label. */
            label: string;
        };
        /** @description UI-facing business permission module metadata. */
        PermissionModuleResponse: {
            /** @description Short description for UI presentation. */
            description: string;
            /** @description Module key stored in `role.permissions`. */
            key: string;
            /** @description Human-readable label. */
            label: string;
            /** @description Allowed actions for the module. */
            permissions: components["schemas"]["PermissionActionResponse"][];
        };
        /** @description Product list response DTO (includes variant count). */
        ProductListResponse: {
            /** @description Variant count. */
            _count: components["schemas"]["VariantCount"];
            /** @description Optional barcode. */
            barcode?: string | null;
            /**
             * Format: int64
             * @description Base selling price.
             */
            basePrice: number;
            brand?: null | components["schemas"]["BrandSummary"];
            /** @description Brand ID. */
            brandId?: string | null;
            category?: null | components["schemas"]["CategorySummary"];
            /** @description Category ID. */
            categoryId?: string | null;
            /**
             * Format: int64
             * @description Cost price.
             */
            costPrice?: number | null;
            /** @description Record creation timestamp. */
            createdAt: string;
            /** @description Optional product description. */
            description?: string | null;
            /** @description Product ID. */
            id: string;
            /** @description Image URL. */
            imageUrl?: string | null;
            /** @description Whether the product is featured. */
            isFeatured: boolean;
            /** @description Product name. */
            name: string;
            /** @description Owning organization ID. */
            organizationId: string;
            /** @description Stock keeping unit. */
            sku: string;
            /** @description Tags for search and filtering. */
            tags?: string[] | null;
            /** @description Record last-update timestamp. */
            updatedAt: string;
        };
        /** @description Full product response DTO. */
        ProductResponse: {
            /** @description Optional barcode. */
            barcode?: string | null;
            /**
             * Format: int64
             * @description Base selling price in smallest currency unit.
             */
            basePrice: number;
            brand?: null | components["schemas"]["BrandSummary"];
            /** @description Brand ID. */
            brandId?: string | null;
            category?: null | components["schemas"]["CategorySummary"];
            /** @description Category ID. */
            categoryId?: string | null;
            /**
             * Format: int64
             * @description Optional cost price in smallest currency unit.
             */
            costPrice?: number | null;
            /** @description Record creation timestamp. */
            createdAt: string;
            /** @description Soft-delete timestamp. */
            deletedAt?: string | null;
            /** @description Optional product description. */
            description?: string | null;
            /** @description Dimensions as JSON. */
            dimensions?: unknown;
            /** @description Product ID. */
            id: string;
            /** @description Image URL. */
            imageUrl?: string | null;
            /** @description Whether the product is featured. */
            isFeatured: boolean;
            /**
             * Format: int64
             * @description Minimum stock level threshold.
             */
            minStockLevel: number;
            /** @description Product name. */
            name: string;
            /** @description Owning organization ID. */
            organizationId: string;
            /** @description Stock keeping unit. */
            sku: string;
            /** @description Tags for search and filtering. */
            tags?: string[] | null;
            /** @description Whether inventory tracking is enabled. */
            trackInventory: boolean;
            /** @description Record last-update timestamp. */
            updatedAt: string;
            /**
             * Format: double
             * @description Weight in kilograms.
             */
            weight?: number | null;
        };
        /** @description Production run response. */
        ProductionRunResponse: {
            /**
             * Format: int64
             * @description Actual cost.
             */
            actualCost?: number | null;
            /** @description BOM ID. */
            bomId: string;
            /** @description Completed timestamp. */
            completedAt?: string | null;
            /** @description Creation timestamp. */
            createdAt: string;
            /** @description User who created this run. */
            createdBy?: string | null;
            /**
             * Format: int64
             * @description Estimated cost.
             */
            estimatedCost?: number | null;
            /** @description Unique identifier. */
            id: string;
            /** @description Organization ID. */
            organizationId: string;
            /**
             * Format: double
             * @description Quantity produced.
             */
            quantityProduced: number;
            /** @description Started timestamp. */
            startedAt?: string | null;
            /** @description Status. */
            status: string;
            /** @description Last update timestamp. */
            updatedAt: string;
        };
        /** @description Production run with consumptions. */
        ProductionRunWithConsumptionResponse: components["schemas"]["ProductionRunResponse"] & {
            /** @description List of consumption records. */
            consumptions: components["schemas"]["ConsumptionResponse"][];
        };
        /** @description Request body for `POST /api/auth/refresh`. */
        RefreshRequest: {
            /** @description The refresh token issued during login or a previous refresh. */
            refreshToken: string;
        };
        /** @description Request body for `POST /api/auth/register`. */
        RegisterRequest: {
            /**
             * @description User email address.
             * @example newuser@sakaloka.id
             */
            email: string;
            /**
             * @description Full name of the user.
             * @example Budi Santoso
             */
            fullName: string;
            /**
             * @description Name of the organization to create or join.
             * @example Warung Budi
             */
            organizationName: string;
            /**
             * @description Plaintext password (must meet complexity rules).
             * @example S3cureP@ssw0rd!
             */
            password: string;
        };
        /** @description Full role response DTO. */
        RoleResponse: {
            /** @description Record creation timestamp. */
            createdAt: string;
            /** @description User who created this role. */
            createdBy?: string | null;
            /** @description Optional description. */
            description?: string | null;
            /** @description Role ID. */
            id: string;
            /** @description Whether the role is active. */
            isActive: boolean;
            /** @description Whether this is a system-defined role. */
            isSystemRole: boolean;
            /** @description Role name. */
            name: string;
            /** @description Organization ID. */
            organizationId: string;
            /** @description JSON permissions for this role. */
            permissions?: unknown;
            /** @description Record last-update timestamp. */
            updatedAt: string;
        };
        /** @description Abbreviated role data included in auth responses. */
        RoleSummary: {
            /** @description Role ID. */
            id: string;
            /** @description Role name. */
            name: string;
            /** @description List of permission strings. */
            permissions: unknown;
        };
        /** @description Request body to select / switch to a different organization. */
        SelectOrgRequest: {
            /** @description ID of the organization to switch to. */
            organizationId: string;
        };
        /** @description Stock movement history entry response DTO. */
        StockHistoryResponse: {
            /** @description Record creation timestamp. */
            createdAt: string;
            /** @description User who created the movement. */
            createdBy?: string | null;
            /** @description Movement ID. */
            id: string;
            /** @description Inventory item ID. */
            inventoryItemId: string;
            /** @description Type of movement (purchase, sale, adjustment, etc.). */
            movementType: string;
            /** @description Optional notes. */
            notes?: string | null;
            /**
             * Format: int32
             * @description Quantity moved.
             */
            quantity: number;
            /** @description Optional reference document ID. */
            referenceId?: string | null;
            /** @description Optional reference type (order, purchase_order). */
            referenceType?: string | null;
        };
        /** @description Full stock (inventory item) response DTO. */
        StockResponse: {
            /** @description Record creation timestamp. */
            createdAt: string;
            /** @description Inventory item ID. */
            id: string;
            /** @description Optional storage location identifier. */
            location?: string | null;
            /**
             * Format: int32
             * @description Maximum stock level.
             */
            maxStockLevel?: number | null;
            /**
             * Format: int32
             * @description Minimum stock level threshold.
             */
            minStockLevel: number;
            /** @description Organization ID. */
            organizationId: string;
            /** @description Product ID. */
            productId: string;
            /**
             * Format: int32
             * @description Quantity available for sale.
             */
            quantityAvailable: number;
            /**
             * Format: int32
             * @description Quantity currently on hand.
             */
            quantityOnHand: number;
            /**
             * Format: int32
             * @description Quantity reserved for pending orders.
             */
            quantityReserved: number;
            /**
             * Format: int32
             * @description Reorder point.
             */
            reorderPoint?: number | null;
            /** @description Optional SKU override at inventory level. */
            sku?: string | null;
            /** @description Record last-update timestamp. */
            updatedAt: string;
        };
        /** @description Request to update a BOM item. */
        UpdateBomItemRequest: {
            /** @description Optional notes. */
            notes?: string | null;
            /**
             * Format: double
             * @description Quantity needed.
             */
            quantity?: number | null;
            /** @description Unit of measure. */
            unit?: string | null;
            /**
             * Format: double
             * @description Waste percentage.
             */
            wastePercent?: number | null;
            /**
             * Format: double
             * @description Yield percentage.
             */
            yieldPercent?: number | null;
        };
        /** @description Request to update a BOM. */
        UpdateBomRequest: {
            /** @description Effective from date. */
            effectiveFrom?: string | null;
            /** @description Effective to date. */
            effectiveTo?: string | null;
            /** @description Name of the BOM. */
            name?: string | null;
            /** @description Optional notes. */
            notes?: string | null;
            /** @description Status. */
            status?: string | null;
            /**
             * Format: int64
             * @description Total cost.
             */
            totalCost?: number | null;
            /** @description Version string. */
            version?: string | null;
        };
        /** @description Request body for updating a brand (all fields optional). */
        UpdateBrandRequest: {
            /** @description Updated description. */
            description?: string | null;
            /** @description Updated logo URL. */
            logo?: string | null;
            /** @description Updated brand name. */
            name?: string | null;
            /** @description Updated website URL. */
            website?: string | null;
        };
        /** @description Request body for updating a category (all fields optional). */
        UpdateCategoryRequest: {
            /** @description Updated description. */
            description?: string | null;
            /** @description Updated image URL. */
            imageUrl?: string | null;
            /** @description Updated category name. */
            name?: string | null;
            /** @description Updated parent category ID. */
            parentId?: string | null;
        };
        /** @description Request body for updating an order. */
        UpdateOrderRequest: {
            /** @description Updated customer name. */
            customerName?: string | null;
            /** @description Updated notes. */
            notes?: string | null;
            /**
             * Format: int64
             * @description Amount paid (for partial payments).
             */
            paidAmount?: number | null;
            /** @description Updated payment method. */
            paymentMethod?: string | null;
            /** @description Updated payment status. */
            paymentStatus?: string | null;
            /** @description Updated status. */
            status?: string | null;
            /** @description Updated table number. */
            tableNumber?: string | null;
        };
        /** @description Request body for updating an organization (all fields optional). */
        UpdateOrgRequest: {
            /** @description Updated physical address. */
            address?: string | null;
            /** @description Updated city. */
            city?: string | null;
            /** @description Updated organization code. */
            code?: string | null;
            /** @description Updated country. */
            country?: string | null;
            /** @description Updated description. */
            description?: string | null;
            /** @description Updated contact email. */
            email?: string | null;
            /** @description Updated active flag. */
            isActive?: boolean | null;
            /** @description Updated logo URL. */
            logo?: string | null;
            /** @description Updated organization name. */
            name?: string | null;
            /** @description Updated contact phone. */
            phone?: string | null;
            /** @description Updated postal code. */
            postalCode?: string | null;
            /** @description Updated business registration number. */
            registrationNumber?: string | null;
            /** @description Updated JSON settings. */
            settings?: unknown;
            /** @description Updated state/province. */
            state?: string | null;
            /** @description Updated tax identification number. */
            taxNumber?: string | null;
            /** @description Updated organization type. */
            type?: string | null;
            /** @description Updated website URL. */
            website?: string | null;
        };
        /** @description Request body for updating a product (all fields optional). */
        UpdateProductRequest: {
            /** @description Updated barcode. */
            barcode?: string | null;
            /**
             * Format: int64
             * @description Updated base price.
             */
            basePrice?: number | null;
            /** @description Updated brand ID. */
            brandId?: string | null;
            /** @description Updated category ID. */
            categoryId?: string | null;
            /**
             * Format: int64
             * @description Updated cost price.
             */
            costPrice?: number | null;
            /** @description Updated description. */
            description?: string | null;
            /** @description Updated dimensions. */
            dimensions?: unknown;
            /** @description Updated image URL. */
            imageUrl?: string | null;
            /** @description Updated is_featured flag. */
            isFeatured?: boolean | null;
            /**
             * Format: int64
             * @description Updated minimum stock level.
             */
            minStockLevel?: number | null;
            /** @description Updated product name. */
            name?: string | null;
            /** @description Updated SKU. */
            sku?: string | null;
            /** @description Updated tags. */
            tags?: string[] | null;
            /** @description Updated track_inventory flag. */
            trackInventory?: boolean | null;
            /**
             * Format: double
             * @description Updated weight.
             */
            weight?: number | null;
        };
        /** @description Request to update a production run. */
        UpdateProductionRunRequest: {
            /**
             * Format: int64
             * @description Actual cost.
             */
            actualCost?: number | null;
            /** @description Completed timestamp. */
            completedAt?: string | null;
            /**
             * Format: int64
             * @description Estimated cost.
             */
            estimatedCost?: number | null;
            /**
             * Format: double
             * @description Quantity produced.
             */
            quantityProduced?: number | null;
            /** @description Started timestamp. */
            startedAt?: string | null;
            /** @description Status. */
            status?: string | null;
        };
        /** @description Request body for updating a role (all fields optional). */
        UpdateRoleRequest: {
            /** @description Updated active flag. */
            isActive?: boolean | null;
            /** @description Updated role name. */
            name?: string | null;
            /** @description Updated permissions. */
            permissions?: unknown;
        };
        /** @description Request body for updating a user (all fields optional). */
        UpdateUserRequest: {
            /** @description Updated email. */
            email?: string | null;
            /** @description Updated full name. */
            fullName?: string | null;
            /** @description Updated active flag. */
            isActive?: boolean | null;
            /** @description Updated plaintext password. */
            password?: string | null;
            /** @description Updated role ID. */
            roleId?: string | null;
        };
        /** @description User profile embedded in the login response. */
        UserProfile: {
            /** @description Email address. */
            email: string;
            /** @description Full name. */
            fullName: string;
            /** @description User primary key. */
            id: string;
            /** @description Summary of the user's organization. */
            organization: components["schemas"]["OrgSummary"];
            /** @description Arbitrary user preferences (JSON). */
            preferences: unknown;
            /** @description Summary of the user's role. */
            role: components["schemas"]["RoleSummary"];
        };
        /** @description Full user response DTO (password hash is never serialized). */
        UserResponse: {
            /** @description Record creation timestamp. */
            createdAt: string;
            /** @description Email address. */
            email: string;
            /** @description Full name. */
            fullName?: string | null;
            /** @description User ID. */
            id: string;
            /** @description Whether the user is active. */
            isActive: boolean;
            /** @description Last login timestamp. */
            lastLoginAt?: string | null;
            /** @description Organization ID. */
            organizationId?: string | null;
            /** @description Role ID. */
            roleId?: string | null;
            /** @description Record last-update timestamp. */
            updatedAt: string;
        };
        /** @description Variant count for list endpoints. */
        VariantCount: {
            /**
             * Format: int64
             * @description Number of variants.
             */
            variants: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
