/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request body for adjusting stock levels. */
        AdjustStockRequest: {
            /** @description Type of adjustment (purchase, sale, adjustment, damage, return). */
            movementType: string;
            /** @description Optional notes. */
            notes?: string | null;
            /**
             * Format: int32
             * @description Signed quantity to adjust (positive = add, negative = remove).
             */
            quantity: number;
            /** @description Reason for the adjustment. */
            reason: string;
            /** @description Optional reference string. */
            reference?: string | null;
        };
        /** @description Full brand response DTO. */
        BrandResponse: {
            /**
             * Format: date-time
             * @description Record creation timestamp.
             */
            createdAt: string;
            /**
             * Format: uuid
             * @description User who created this brand.
             */
            createdBy?: string | null;
            /** @description Optional description. */
            description?: string | null;
            /**
             * Format: uuid
             * @description Brand ID.
             */
            id: string;
            /** @description Optional logo URL. */
            logo?: string | null;
            /** @description Brand name. */
            name: string;
            /**
             * Format: uuid
             * @description Owning organization ID.
             */
            organizationId: string;
            /** @description URL-friendly slug. */
            slug: string;
            /**
             * Format: date-time
             * @description Record last-update timestamp.
             */
            updatedAt: string;
            /** @description Optional website URL. */
            website?: string | null;
        };
        /** @description Abbreviated brand info embedded in product responses. */
        BrandSummary: {
            /**
             * Format: uuid
             * @description Brand ID.
             */
            id: string;
            /** @description Brand name. */
            name: string;
        };
        /** @description Full category response DTO. */
        CategoryResponse: {
            /**
             * Format: date-time
             * @description Record creation timestamp.
             */
            createdAt: string;
            /**
             * Format: uuid
             * @description User who created this category.
             */
            createdBy?: string | null;
            /** @description Optional description. */
            description?: string | null;
            /**
             * Format: uuid
             * @description Category ID.
             */
            id: string;
            /** @description Optional image URL. */
            imageUrl?: string | null;
            /** @description Category name. */
            name: string;
            /**
             * Format: uuid
             * @description Owning organization ID.
             */
            organizationId: string;
            /**
             * Format: uuid
             * @description Optional parent category ID for hierarchy.
             */
            parentId?: string | null;
            /** @description URL-friendly slug. */
            slug: string;
            /**
             * Format: date-time
             * @description Record last-update timestamp.
             */
            updatedAt: string;
        };
        /** @description Abbreviated category info embedded in product responses. */
        CategorySummary: {
            /**
             * Format: uuid
             * @description Category ID.
             */
            id: string;
            /** @description Category name. */
            name: string;
        };
        /** @description Request body for creating a brand. */
        CreateBrandRequest: {
            /** @description Optional description. */
            description?: string | null;
            /** @description Optional logo URL. */
            logo?: string | null;
            /** @description Brand name. */
            name: string;
            /** @description Optional website URL. */
            website?: string | null;
        };
        /** @description Request body for creating a category. */
        CreateCategoryRequest: {
            /** @description Optional description. */
            description?: string | null;
            /** @description Optional image URL. */
            imageUrl?: string | null;
            /** @description Category name. */
            name: string;
            /**
             * Format: uuid
             * @description Optional parent category ID.
             */
            parentId?: string | null;
        };
        /** @description Order item within a create order request. */
        CreateOrderItemRequest: {
            /** @description Optional custom item name override. */
            itemName?: string | null;
            /**
             * Format: uuid
             * @description Product ID.
             */
            productId: string;
            /**
             * Format: int32
             * @description Quantity to order.
             */
            quantity: number;
        };
        /** @description Request body for creating an order. */
        CreateOrderRequest: {
            /** @description Optional walk-in customer name. */
            customerName?: string | null;
            /** @description Order items. */
            items: components["schemas"]["CreateOrderItemRequest"][];
            /** @description Optional notes. */
            notes?: string | null;
            /** @description Optional payment method. */
            paymentMethod?: string | null;
            /** @description Optional table number. */
            tableNumber?: string | null;
            /** @description Order type (dine_in, takeaway, delivery). */
            type: string;
        };
        /** @description Request body for creating an organization. */
        CreateOrgRequest: {
            /** @description Optional physical address. */
            address?: string | null;
            /** @description Optional city. */
            city?: string | null;
            /** @description Optional organization code. */
            code?: string | null;
            /** @description Optional country. */
            country?: string | null;
            /** @description Optional description. */
            description?: string | null;
            /** @description Optional contact email. */
            email?: string | null;
            /** @description Optional logo URL. */
            logo?: string | null;
            /** @description Organization name. */
            name: string;
            /**
             * Format: uuid
             * @description Optional parent organization ID.
             */
            parentId?: string | null;
            /** @description Optional contact phone. */
            phone?: string | null;
            /** @description Optional postal code. */
            postalCode?: string | null;
            /** @description Optional business registration number. */
            registrationNumber?: string | null;
            /** @description Optional JSON settings. */
            settings?: unknown;
            /** @description Optional state/province. */
            state?: string | null;
            /** @description Optional tax identification number. */
            taxNumber?: string | null;
            /** @description Organization type (e.g. "restaurant", "retail"). */
            type: string;
            /** @description Optional website URL. */
            website?: string | null;
        };
        /** @description Request body for creating a product. */
        CreateProductRequest: {
            /** @description Optional barcode. */
            barcode?: string | null;
            /**
             * Format: int64
             * @description Base selling price in smallest currency unit.
             */
            basePrice: number;
            /**
             * Format: uuid
             * @description Optional brand ID.
             */
            brandId?: string | null;
            /**
             * Format: uuid
             * @description Optional category ID.
             */
            categoryId?: string | null;
            /**
             * Format: int64
             * @description Optional cost price.
             */
            costPrice?: number | null;
            /** @description Optional product description. */
            description?: string | null;
            /** @description Optional dimensions as JSON. */
            dimensions?: unknown;
            /** @description Optional image URL. */
            imageUrl?: string | null;
            /** @description Whether the product is featured (default false). */
            isFeatured?: boolean | null;
            /**
             * Format: int32
             * @description Optional minimum stock level.
             */
            minStockLevel?: number | null;
            /** @description Product name. */
            name: string;
            /** @description Stock keeping unit (unique within organization). */
            sku: string;
            /** @description Optional tags as JSON. */
            tags?: unknown;
            /** @description Whether to track inventory (default false). */
            trackInventory?: boolean | null;
            /**
             * Format: double
             * @description Optional weight in kilograms.
             */
            weight?: number | null;
        };
        /** @description Request body for creating a role. */
        CreateRoleRequest: {
            /** @description Whether the role should be active immediately. */
            isActive?: boolean | null;
            /** @description Role name. */
            name: string;
            /** @description JSON permissions to assign. */
            permissions: unknown;
        };
        /** @description Request body for creating a user. */
        CreateUserRequest: {
            /** @description Email address. */
            email: string;
            /** @description Full name. */
            fullName: string;
            /** @description Whether the user should be active immediately. */
            isActive?: boolean | null;
            /** @description Plaintext password (will be hashed before storage). */
            password: string;
            /**
             * Format: uuid
             * @description Role ID to assign.
             */
            roleId: string;
        };
        /** @description Active sort filters echoed back to the frontend. */
        ListFilters: {
            /** @description Column used for sorting. */
            sortBy: string;
            /** @description Sort direction (`asc` or `desc`). */
            sortOrder: string;
        };
        /** @description Request body for `POST /api/auth/login`. */
        LoginRequest: {
            /**
             * @description User email address.
             * @example admin@sakaloka.id
             */
            email: string;
            /**
             * @description Plaintext password.
             * @example sakaloka-dev
             */
            password: string;
        };
        /** @description Successful login / refresh response. */
        LoginResponse: {
            /** @description Short-lived access JWT. */
            access_token: string;
            /** @description Long-lived refresh token. */
            refresh_token: string;
            /** @description Authenticated user profile. */
            user: components["schemas"]["UserProfile"];
        };
        /** @description POS menu item DTO (product + pricing for the order screen). */
        MenuResponse: {
            /**
             * Format: int64
             * @description Base selling price.
             */
            basePrice: number;
            /**
             * Format: uuid
             * @description Category ID.
             */
            categoryId?: string | null;
            /** @description Category name (if resolved). */
            categoryName?: string | null;
            /**
             * Format: uuid
             * @description Product ID.
             */
            id: string;
            /** @description Image URL. */
            imageUrl?: string | null;
            /** @description Whether the product is featured. */
            isFeatured: boolean;
            /** @description Product name. */
            name: string;
            /** @description Product SKU. */
            sku: string;
        };
        /** @description Single order item response DTO. */
        OrderItemResponse: {
            /**
             * Format: date-time
             * @description Record creation timestamp.
             */
            createdAt: string;
            /**
             * Format: uuid
             * @description Order item ID.
             */
            id: string;
            /** @description Item name snapshot. */
            itemName: string;
            /**
             * Format: uuid
             * @description Parent order ID.
             */
            orderId: string;
            /**
             * Format: uuid
             * @description Product ID.
             */
            productId: string;
            /**
             * Format: int32
             * @description Quantity ordered.
             */
            quantity: number;
            /**
             * Format: int64
             * @description Total price for this line.
             */
            totalPrice: number;
            /**
             * Format: int64
             * @description Unit price at time of order.
             */
            unitPrice: number;
        };
        /** @description Full order response DTO. */
        OrderResponse: {
            /**
             * Format: date-time
             * @description Record creation timestamp.
             */
            createdAt: string;
            /**
             * Format: uuid
             * @description User who created this order.
             */
            createdBy?: string | null;
            /**
             * Format: uuid
             * @description Optional customer user ID.
             */
            customerId?: string | null;
            /** @description Walk-in customer name. */
            customerName?: string | null;
            /**
             * Format: int64
             * @description Discount amount.
             */
            discountAmount: number;
            /**
             * Format: uuid
             * @description Order ID.
             */
            id: string;
            /** @description Order items (populated when fetching a single order). */
            items?: components["schemas"]["OrderItemResponse"][] | null;
            /** @description Order notes. */
            notes?: string | null;
            /** @description Unique order number. */
            orderNumber: string;
            /**
             * Format: uuid
             * @description Organization ID.
             */
            organizationId: string;
            /**
             * Format: int64
             * @description Amount already paid.
             */
            paidAmount: number;
            /** @description Payment method. */
            paymentMethod?: string | null;
            /** @description Payment status. */
            paymentStatus: string;
            /** @description Order status. */
            status: string;
            /**
             * Format: int64
             * @description Subtotal before tax/discounts.
             */
            subtotal: number;
            /** @description Table number for dine-in orders. */
            tableNumber?: string | null;
            /**
             * Format: int64
             * @description Tax amount.
             */
            taxAmount: number;
            /**
             * Format: int64
             * @description Total amount after tax and discounts.
             */
            totalAmount: number;
            /** @description Order type (dine_in, takeaway, delivery). */
            type: string;
            /**
             * Format: date-time
             * @description Record last-update timestamp.
             */
            updatedAt: string;
            /**
             * Format: uuid
             * @description User who last updated this order.
             */
            updatedBy?: string | null;
        };
        /** @description Abbreviated organization data included in auth responses. */
        OrgSummary: {
            /** @description Organization ID. */
            id: string;
            /** @description Organization name. */
            name: string;
            /** @description Organization type. */
            type: string;
        };
        /** @description Full organization response DTO. */
        OrganizationResponse: {
            /** @description Optional physical address. */
            address?: string | null;
            /** @description Optional city. */
            city?: string | null;
            /** @description Optional organization code. */
            code?: string | null;
            /** @description Optional country. */
            country?: string | null;
            /**
             * Format: date-time
             * @description Record creation timestamp.
             */
            createdAt: string;
            /** @description Optional description. */
            description?: string | null;
            /** @description Optional contact email. */
            email?: string | null;
            /**
             * Format: uuid
             * @description Organization ID.
             */
            id: string;
            /** @description Whether the organization is active. */
            isActive: boolean;
            /** @description Optional logo URL. */
            logo?: string | null;
            /** @description Organization name. */
            name: string;
            /**
             * Format: uuid
             * @description Optional owner user ID.
             */
            ownerId?: string | null;
            /**
             * Format: uuid
             * @description Optional parent organization ID.
             */
            parentId?: string | null;
            /** @description Optional contact phone. */
            phone?: string | null;
            /** @description Optional postal code. */
            postalCode?: string | null;
            /** @description Optional business registration number. */
            registrationNumber?: string | null;
            /** @description Optional JSON settings. */
            settings?: unknown;
            /** @description Optional state/province. */
            state?: string | null;
            /** @description Optional tax identification number. */
            taxNumber?: string | null;
            /** @description Organization type. */
            type: string;
            /**
             * Format: date-time
             * @description Record last-update timestamp.
             */
            updatedAt: string;
            /** @description Optional website URL. */
            website?: string | null;
        };
        /** @description Pagination metadata matching Venus `IPageMeta`. */
        PageMeta: {
            /** @description Whether a next page exists. */
            hasNextPage: boolean;
            /** @description Whether a previous page exists. */
            hasPrevPage: boolean;
            /**
             * Format: int64
             * @description Items per page.
             */
            limit: number;
            /**
             * Format: int64
             * @description Current page number (1-indexed).
             */
            page: number;
            /**
             * Format: int64
             * @description Total number of pages.
             */
            pages: number;
            /**
             * Format: int64
             * @description Total number of matching records.
             */
            total: number;
        };
        /** @description Response listing all available permissions. */
        PermissionsResponse: {
            /** @description List of all known permission strings. */
            permissions: string[];
        };
        /** @description Product list response DTO (includes variant count). */
        ProductListResponse: {
            /** @description Variant count. */
            _count: components["schemas"]["VariantCount"];
            /** @description Optional barcode. */
            barcode?: string | null;
            /**
             * Format: int64
             * @description Base selling price.
             */
            basePrice: number;
            brand?: null | components["schemas"]["BrandSummary"];
            /**
             * Format: uuid
             * @description Brand ID.
             */
            brandId?: string | null;
            category?: null | components["schemas"]["CategorySummary"];
            /**
             * Format: uuid
             * @description Category ID.
             */
            categoryId?: string | null;
            /**
             * Format: int64
             * @description Cost price.
             */
            costPrice?: number | null;
            /**
             * Format: date-time
             * @description Record creation timestamp.
             */
            createdAt: string;
            /** @description Optional product description. */
            description?: string | null;
            /**
             * Format: uuid
             * @description Product ID.
             */
            id: string;
            /** @description Image URL. */
            imageUrl?: string | null;
            /** @description Whether the product is featured. */
            isFeatured: boolean;
            /** @description Product name. */
            name: string;
            /**
             * Format: uuid
             * @description Owning organization ID.
             */
            organizationId: string;
            /** @description Stock keeping unit. */
            sku: string;
            /** @description Tags as JSON. */
            tags?: unknown;
            /**
             * Format: date-time
             * @description Record last-update timestamp.
             */
            updatedAt: string;
        };
        /** @description Full product response DTO. */
        ProductResponse: {
            /** @description Optional barcode. */
            barcode?: string | null;
            /**
             * Format: int64
             * @description Base selling price in smallest currency unit.
             */
            basePrice: number;
            brand?: null | components["schemas"]["BrandSummary"];
            /**
             * Format: uuid
             * @description Brand ID.
             */
            brandId?: string | null;
            category?: null | components["schemas"]["CategorySummary"];
            /**
             * Format: uuid
             * @description Category ID.
             */
            categoryId?: string | null;
            /**
             * Format: int64
             * @description Optional cost price in smallest currency unit.
             */
            costPrice?: number | null;
            /**
             * Format: date-time
             * @description Record creation timestamp.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Soft-delete timestamp.
             */
            deletedAt?: string | null;
            /** @description Optional product description. */
            description?: string | null;
            /** @description Dimensions as JSON. */
            dimensions?: unknown;
            /**
             * Format: uuid
             * @description Product ID.
             */
            id: string;
            /** @description Image URL. */
            imageUrl?: string | null;
            /** @description Whether the product is featured. */
            isFeatured: boolean;
            /**
             * Format: int32
             * @description Minimum stock level threshold.
             */
            minStockLevel?: number | null;
            /** @description Product name. */
            name: string;
            /**
             * Format: uuid
             * @description Owning organization ID.
             */
            organizationId: string;
            /** @description Stock keeping unit. */
            sku: string;
            /** @description Tags as JSON. */
            tags?: unknown;
            /** @description Whether inventory tracking is enabled. */
            trackInventory: boolean;
            /**
             * Format: date-time
             * @description Record last-update timestamp.
             */
            updatedAt: string;
            /**
             * Format: double
             * @description Weight in kilograms.
             */
            weight?: number | null;
        };
        /** @description Request body for `POST /api/auth/refresh`. */
        RefreshRequest: {
            /** @description The refresh token issued during login or a previous refresh. */
            refreshToken: string;
        };
        /** @description Request body for `POST /api/auth/register`. */
        RegisterRequest: {
            /**
             * @description User email address.
             * @example newuser@sakaloka.id
             */
            email: string;
            /**
             * @description Full name of the user.
             * @example Budi Santoso
             */
            fullName: string;
            /**
             * @description Name of the organization to create or join.
             * @example Warung Budi
             */
            organizationName: string;
            /**
             * @description Plaintext password (must meet complexity rules).
             * @example S3cureP@ssw0rd!
             */
            password: string;
        };
        /** @description Full role response DTO. */
        RoleResponse: {
            /**
             * Format: date-time
             * @description Record creation timestamp.
             */
            createdAt: string;
            /**
             * Format: uuid
             * @description User who created this role.
             */
            createdBy?: string | null;
            /**
             * Format: uuid
             * @description Role ID.
             */
            id: string;
            /** @description Whether the role is active. */
            isActive: boolean;
            /** @description Whether this is a system-defined role. */
            isSystemRole: boolean;
            /** @description Role name. */
            name: string;
            /**
             * Format: uuid
             * @description Organization ID.
             */
            organizationId: string;
            /** @description JSON permissions for this role. */
            permissions: unknown;
            /**
             * Format: date-time
             * @description Record last-update timestamp.
             */
            updatedAt: string;
        };
        /** @description Abbreviated role data included in auth responses. */
        RoleSummary: {
            /** @description Role ID. */
            id: string;
            /** @description Role name. */
            name: string;
            /** @description List of permission strings. */
            permissions: unknown;
        };
        /** @description Request body to select / switch to a different organization. */
        SelectOrgRequest: {
            /**
             * Format: uuid
             * @description ID of the organization to switch to.
             */
            organizationId: string;
        };
        /** @description Stock movement history entry response DTO. */
        StockHistoryResponse: {
            /**
             * Format: date-time
             * @description Record creation timestamp.
             */
            createdAt: string;
            /**
             * Format: uuid
             * @description User who created the movement.
             */
            createdBy?: string | null;
            /**
             * Format: uuid
             * @description Movement ID.
             */
            id: string;
            /**
             * Format: uuid
             * @description Inventory item ID.
             */
            inventoryItemId: string;
            /** @description Type of movement (purchase, sale, adjustment, etc.). */
            movementType: string;
            /** @description Optional notes. */
            notes?: string | null;
            /**
             * Format: int32
             * @description Quantity moved.
             */
            quantity: number;
            /**
             * Format: int32
             * @description Signed quantity change.
             */
            quantityChange: number;
            /** @description Reason for the movement. */
            reason: string;
            /** @description Optional reference (order number, PO, etc.). */
            reference?: string | null;
            /**
             * Format: int32
             * @description Inventory after this movement.
             */
            totalAfter: number;
            /**
             * Format: int32
             * @description Inventory before this movement.
             */
            totalBefore: number;
        };
        /** @description Full stock (inventory item) response DTO. */
        StockResponse: {
            /**
             * Format: int64
             * @description Average cost per unit.
             */
            averageCost?: number | null;
            /**
             * Format: date-time
             * @description Record creation timestamp.
             */
            createdAt: string;
            /**
             * Format: uuid
             * @description Inventory item ID.
             */
            id: string;
            /**
             * Format: int64
             * @description Last purchase cost per unit.
             */
            lastCost?: number | null;
            /**
             * Format: date-time
             * @description Timestamp of last stock movement.
             */
            lastMovementAt?: string | null;
            /**
             * Format: uuid
             * @description Optional storage location ID.
             */
            locationId?: string | null;
            /**
             * Format: int32
             * @description Maximum stock level.
             */
            maxStockLevel?: number | null;
            /**
             * Format: int32
             * @description Minimum stock level threshold.
             */
            minStockLevel?: number | null;
            /**
             * Format: uuid
             * @description Organization ID.
             */
            organizationId: string;
            /**
             * Format: uuid
             * @description Product ID.
             */
            productId: string;
            /**
             * Format: int32
             * @description Quantity available for sale.
             */
            quantityAvailable: number;
            /**
             * Format: int32
             * @description Quantity currently on hand.
             */
            quantityOnHand: number;
            /**
             * Format: int32
             * @description Quantity reserved for pending orders.
             */
            quantityReserved: number;
            /**
             * Format: int32
             * @description Reorder point.
             */
            reorderPoint?: number | null;
            /**
             * Format: int32
             * @description Reorder quantity.
             */
            reorderQuantity?: number | null;
            /**
             * Format: date-time
             * @description Record last-update timestamp.
             */
            updatedAt: string;
        };
        /** @description Request body for updating a brand (all fields optional). */
        UpdateBrandRequest: {
            /** @description Updated description. */
            description?: string | null;
            /** @description Updated logo URL. */
            logo?: string | null;
            /** @description Updated brand name. */
            name?: string | null;
            /** @description Updated website URL. */
            website?: string | null;
        };
        /** @description Request body for updating a category (all fields optional). */
        UpdateCategoryRequest: {
            /** @description Updated description. */
            description?: string | null;
            /** @description Updated image URL. */
            imageUrl?: string | null;
            /** @description Updated category name. */
            name?: string | null;
            /**
             * Format: uuid
             * @description Updated parent category ID.
             */
            parentId?: string | null;
        };
        /** @description Request body for updating an order. */
        UpdateOrderRequest: {
            /** @description Updated customer name. */
            customerName?: string | null;
            /** @description Updated notes. */
            notes?: string | null;
            /**
             * Format: int64
             * @description Amount paid (for partial payments).
             */
            paidAmount?: number | null;
            /** @description Updated payment method. */
            paymentMethod?: string | null;
            /** @description Updated payment status. */
            paymentStatus?: string | null;
            /** @description Updated status. */
            status?: string | null;
            /** @description Updated table number. */
            tableNumber?: string | null;
        };
        /** @description Request body for updating an organization (all fields optional). */
        UpdateOrgRequest: {
            /** @description Updated physical address. */
            address?: string | null;
            /** @description Updated city. */
            city?: string | null;
            /** @description Updated organization code. */
            code?: string | null;
            /** @description Updated country. */
            country?: string | null;
            /** @description Updated description. */
            description?: string | null;
            /** @description Updated contact email. */
            email?: string | null;
            /** @description Updated active flag. */
            isActive?: boolean | null;
            /** @description Updated logo URL. */
            logo?: string | null;
            /** @description Updated organization name. */
            name?: string | null;
            /** @description Updated contact phone. */
            phone?: string | null;
            /** @description Updated postal code. */
            postalCode?: string | null;
            /** @description Updated business registration number. */
            registrationNumber?: string | null;
            /** @description Updated JSON settings. */
            settings?: unknown;
            /** @description Updated state/province. */
            state?: string | null;
            /** @description Updated tax identification number. */
            taxNumber?: string | null;
            /** @description Updated organization type. */
            type?: string | null;
            /** @description Updated website URL. */
            website?: string | null;
        };
        /** @description Request body for updating a product (all fields optional). */
        UpdateProductRequest: {
            /** @description Updated barcode. */
            barcode?: string | null;
            /**
             * Format: int64
             * @description Updated base price.
             */
            basePrice?: number | null;
            /**
             * Format: uuid
             * @description Updated brand ID.
             */
            brandId?: string | null;
            /**
             * Format: uuid
             * @description Updated category ID.
             */
            categoryId?: string | null;
            /**
             * Format: int64
             * @description Updated cost price.
             */
            costPrice?: number | null;
            /** @description Updated description. */
            description?: string | null;
            /** @description Updated dimensions. */
            dimensions?: unknown;
            /** @description Updated image URL. */
            imageUrl?: string | null;
            /** @description Updated is_featured flag. */
            isFeatured?: boolean | null;
            /**
             * Format: int32
             * @description Updated minimum stock level.
             */
            minStockLevel?: number | null;
            /** @description Updated product name. */
            name?: string | null;
            /** @description Updated SKU. */
            sku?: string | null;
            /** @description Updated tags. */
            tags?: unknown;
            /** @description Updated track_inventory flag. */
            trackInventory?: boolean | null;
            /**
             * Format: double
             * @description Updated weight.
             */
            weight?: number | null;
        };
        /** @description Request body for updating a role (all fields optional). */
        UpdateRoleRequest: {
            /** @description Updated active flag. */
            isActive?: boolean | null;
            /** @description Updated role name. */
            name?: string | null;
            /** @description Updated permissions. */
            permissions?: unknown;
        };
        /** @description Request body for updating a user (all fields optional). */
        UpdateUserRequest: {
            /** @description Updated email. */
            email?: string | null;
            /** @description Updated full name. */
            fullName?: string | null;
            /** @description Updated active flag. */
            isActive?: boolean | null;
            /** @description Updated plaintext password. */
            password?: string | null;
            /**
             * Format: uuid
             * @description Updated role ID.
             */
            roleId?: string | null;
        };
        /** @description User profile embedded in the login response. */
        UserProfile: {
            /** @description Email address. */
            email: string;
            /** @description Full name. */
            fullName: string;
            /** @description User primary key. */
            id: string;
            /** @description Summary of the user's organization. */
            organization: components["schemas"]["OrgSummary"];
            /** @description Arbitrary user preferences (JSON). */
            preferences: unknown;
            /** @description Summary of the user's role. */
            role: components["schemas"]["RoleSummary"];
        };
        /** @description Full user response DTO (password hash is never serialized). */
        UserResponse: {
            /**
             * Format: date-time
             * @description Record creation timestamp.
             */
            createdAt: string;
            /** @description Email address. */
            email: string;
            /** @description Full name. */
            fullName: string;
            /**
             * Format: uuid
             * @description User ID.
             */
            id: string;
            /** @description Whether the user is active. */
            isActive: boolean;
            /**
             * Format: date-time
             * @description Last login timestamp.
             */
            lastLoginAt?: string | null;
            /**
             * Format: uuid
             * @description Organization ID.
             */
            organizationId: string;
            /**
             * Format: uuid
             * @description Role ID.
             */
            roleId: string;
            /**
             * Format: date-time
             * @description Record last-update timestamp.
             */
            updatedAt: string;
        };
        /** @description Variant count for list endpoints. */
        VariantCount: {
            /**
             * Format: int64
             * @description Number of variants.
             */
            variants: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
